export { default as Home } from './home/Home';
export { default as Signin } from './auth/Signin';
export { default as Signup } from './auth/Signup';
export { default as Browse } from './browse/Browse';
export { default as Cart } from './checkout/Checkout';
export { default as ProductDetail } from './product-detail/ProductDetail';
export { default as Profile } from './profile/Profile';
export { default as Shipping } from './shipping/Shipping';
export { default as Payment } from './payment/Payment';
